sudo: false
services:
  - docker
language: scala
scala:
  - 2.12.10
addons:
  hosts:
    - broker
jdk:
  - openjdk8
  - openjdk11

# I need to update Maven because the `--no-transfer-progress` option is not available on the pre-installed version.
before_install:
  - wget http://apache.mirror.gtcomm.net/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
  - tar xzvf apache-maven-3.6.2-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.2/bin:$PATH
  - mvn -v

script:
  - git clone https://github.com/simplesourcing/simplesource-examples
  - cd simplesource-examples
  - mvn install --no-transfer-progress
  - cd ..
  - git clone https://github.com/guizmaii/simplesource.git
  - cd simplesource
  - git checkout eventsourceapp_builder
  - mvn install --no-transfer-progress
  - cd ..
  - docker-compose down
  - docker-compose up -d --force-recreate --renew-anon-volumes
  - sbt ++$TRAVIS_SCALA_VERSION clean gatling:test
  - docker-compose down
  - docker-compose up -d --force-recreate --renew-anon-volumes
  - sbt ++$TRAVIS_SCALA_VERSION clean gatling-it:test


# Comes from: https://github.com/http4s/http4s/blob/master/.travis.yml#L109
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"
    - "$HOME/.m2"