sudo: false
services:
  - docker
language: scala
scala:
  - 2.12.10
script:
  - docker-compose up
  - sbt ++$TRAVIS_SCALA_VERSION clean gatling:test
  - docker-compose down
  - docker-compose up
  - sbt ++$TRAVIS_SCALA_VERSION clean gatling-it:test
jdk:
  - openjdk8
  - openjdk11

# Comes from: https://github.com/http4s/http4s/blob/master/.travis.yml#L109
cache:
  directories:
    - "$HOME/.cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"