---
Resources:
  SimpleBenchsPrivateVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/Resource
  SimpleBenchsPublicSubnet1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/Subnet
  SimpleBenchsPublicSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/RouteTable
  SimpleBenchsPublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet1RouteTable
      SubnetId:
        Ref: SimpleBenchsPublicSubnet1Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/RouteTableAssociation
  SimpleBenchsPublicSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SimpleBenchsIGW
    DependsOn:
      - SimpleBenchsVPCGW
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/DefaultRoute
  SimpleBenchsPublicSubnet1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/EIP
  SimpleBenchsPublicSubnet1NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - SimpleBenchsPublicSubnet1EIP
          - AllocationId
      SubnetId:
        Ref: SimpleBenchsPublicSubnet1Subnet
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet1/NATGateway
  SimpleBenchsPublicSubnet2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.32.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2b
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2/Subnet
  SimpleBenchsPublicSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2/RouteTable
  SimpleBenchsPublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet2RouteTable
      SubnetId:
        Ref: SimpleBenchsPublicSubnet2Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2/RouteTableAssociation
  SimpleBenchsPublicSubnet2DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SimpleBenchsIGW
    DependsOn:
      - SimpleBenchsVPCGW
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet2/DefaultRoute
  SimpleBenchsPublicSubnet3Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.64.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3
        - Key: aws-cdk:subnet-name
          Value: Public
        - Key: aws-cdk:subnet-type
          Value: Public
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3/Subnet
  SimpleBenchsPublicSubnet3RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3/RouteTable
  SimpleBenchsPublicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet3RouteTable
      SubnetId:
        Ref: SimpleBenchsPublicSubnet3Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3/RouteTableAssociation
  SimpleBenchsPublicSubnet3DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPublicSubnet3RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: SimpleBenchsIGW
    DependsOn:
      - SimpleBenchsVPCGW
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PublicSubnet3/DefaultRoute
  SimpleBenchsPrivateSubnet1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.96.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2a
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1/Subnet
  SimpleBenchsPrivateSubnet1RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1/RouteTable
  SimpleBenchsPrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet1RouteTable
      SubnetId:
        Ref: SimpleBenchsPrivateSubnet1Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1/RouteTableAssociation
  SimpleBenchsPrivateSubnet1DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet1RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SimpleBenchsPublicSubnet1NATGateway
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet1/DefaultRoute
  SimpleBenchsPrivateSubnet2Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.128.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2/Subnet
  SimpleBenchsPrivateSubnet2RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2/RouteTable
  SimpleBenchsPrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet2RouteTable
      SubnetId:
        Ref: SimpleBenchsPrivateSubnet2Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2/RouteTableAssociation
  SimpleBenchsPrivateSubnet2DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet2RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SimpleBenchsPublicSubnet1NATGateway
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet2/DefaultRoute
  SimpleBenchsPrivateSubnet3Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.160.0/19
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      AvailabilityZone: ap-southeast-2c
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3
        - Key: aws-cdk:subnet-name
          Value: Private
        - Key: aws-cdk:subnet-type
          Value: Private
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3/Subnet
  SimpleBenchsPrivateSubnet3RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3/RouteTable
  SimpleBenchsPrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet3RouteTable
      SubnetId:
        Ref: SimpleBenchsPrivateSubnet3Subnet
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3/RouteTableAssociation
  SimpleBenchsPrivateSubnet3DefaultRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: SimpleBenchsPrivateSubnet3RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: SimpleBenchsPublicSubnet1NATGateway
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/PrivateSubnet3/DefaultRoute
  SimpleBenchsIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Simplesourcing-Vpc-Stack/SimpleBenchs
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/IGW
  SimpleBenchsVPCGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: SimpleBenchsPrivateVpc
      InternetGatewayId:
        Ref: SimpleBenchsIGW
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/SimpleBenchs/VPCGW
  SimpleBenchsAllowAllInternalVpcTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Simplesourcing-Vpc-Stack/allow-all-internal-vpc-traffic
      GroupName: AllowAllInternalVpcTraffic
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic by default
          IpProtocol: "-1"
      SecurityGroupIngress:
        - CidrIp: 10.0.0.0/16
          Description: allow-all-in-vpc
          FromPort: 0
          IpProtocol: tcp
          ToPort: 65535
      VpcId:
        Ref: SimpleBenchsPrivateVpc
    Metadata:
      aws:cdk:path: Simplesourcing-Vpc-Stack/allow-all-internal-vpc-traffic/Resource
